<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ER8E34F9" failures="1" tests="2" name="Test1" time="22.829" errors="0" timestamp="2021-12-30T21:01:26 IST">
  <testcase classname="selenium.ProperScript" name="invalidCredential" time="7.407">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]
at selenium.ProperScript.invalidCredential(ProperScript.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- invalidCredential -->
  <testcase classname="selenium.ProperScript" name="validCredential" time="10.954"/>
</testsuite> <!-- Test1 -->
